const images = {
  logos: {
    acougue:require('../../assets/acougue.jpg'),
    advogados:require('../../assets/advogados.jpg'),
    agronegocio:require('../../assets/agronegocio.jpg'),
    animais: require('../../assets/animais.jpg'),
    antiguidades:require('../../assets/antiguidades.jpg'),
    automotivo:require('../../assets/automotivo.jpg'),
    bares:require('../../assets/bares.jpg'),
    bebes:require('../../assets/bebes.jpg'),
    beleza:require('../../assets/beleza.jpg'),
    bolsas:require('../../assets/bolsas.jpg'),
    brinquedos:require('../../assets/brinquedos.jpg'),
    buffet:require('../../assets/buffet.jpg'),
    cabelereiro:require('../../assets/cabelereiro.jpg'),
    calcados:require('../../assets/calcados.jpg'),
    casajardim:require('../../assets/casa-jardim.jpg'),
    celular:require('../../assets/celular.jpg'),
    ceramica:require('../../assets/ceramica.jpg'),
    construcao:require('../../assets/construcao.jpg'),
    consultorio:require('../../assets/consultorio.jpg'),
    contabilidade:require('../../assets/contabilidade.jpg'),
    educacao:require('../../assets/educacao.jpg'),
    eletrica:require('../../assets/Eletrica.jpg'),
    eletrônicos:require('../../assets/eletronicos.jpg'),
    emprego:require('../../assets/emprego.jpg'),
    esportes:require('../../assets/esportes.jpg'),
    eventos:require('../../assets/eventos.jpg'),
    farmacia:require('../../assets/farmacia.jpg'),
    flores:require('../../assets/flores.jpg'),
    fotofilmagens:require('../../assets/fotos-filmagens.jpg'),
    grafica:require('../../assets/grafica.jpg'),
    idiomas:require('../../assets/idiomas.jpg'),
    imoveis:require('../../assets/imoveis.jpg'),
    informatica:require('../../assets/informatica.jpg'),
    internet:require('../../assets/internet.jpg'),
    jogos:require('../../assets/jogos.jpg'),
    livros:require('../../assets/livros.jpg'),
    motos:require('../../assets/motos.jpg'),
    moveis:require('../../assets/moveis.jpg'),
    negocios:require('../../assets/negocios.jpg'),
    pesca:require('../../assets/pesca.jpg'),
    pizzaria:require('../../assets/pizzaria.jpg'),
    relogios:require('../../assets/relogios.jpg'),
    restaurantes:require('../../assets/restaurantes.jpg'),
    saude:require('../../assets/saude.jpg'),
    servicos:require('../../assets/servicos.jpg'),
    supermercado:require('../../assets/supermercado.jpg'),
    turismo:require('../../assets/turismo.jpg'),
    vestuario:require('../../assets/vestuario.jpg'),
    vidracaria:require('../../assets/vidracaria.jpg')
  }
};

export default images;